# Generated by Django 2.1.9 on 2019-06-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0070_make_concept_ids_64_bit'),
        ('catmaid', '0069_fix_on_edit_treenode_connector_update_edges'),
    ]

    operations = [
    ]
